# Vert.x Application Configuration
# This file configures the application using SmallRye Config with YAML format
# Environment variables will override these values using standard naming convention
# Example: app.server.port -> APP_SERVER_PORT

app:
  server:
    port: 8080
    host: 0.0.0.0
    request-timeout-ms: 30000
    api-prefix: /api
    enable-cors: true
  
  worker:
    pool-size: 10
    max-execute-time: 60000
  
  security:
    enable-auth: true
    jwt-secret: your-secret-key
    jwt-expiration-ms: 86400000
    public-paths: /api/common
  
  logging:
    enable-request-logging: true
    log-request-bodies: false
    log-level: INFO
  
  service:
    default-timeout-ms: 500
    base-delay-ms: 100
    max-delay-variance-ms: 200
    min-id-range: 1000
    max-id-range: 9999
    user-fetch-base-delay-ms: 50
    user-fetch-max-variance-ms: 100
    create-base-delay-ms: 200
    create-max-variance-ms: 300
    product-create-base-delay-ms: 300
    product-create-max-variance-ms: 400
    update-base-delay-ms: 150
    update-max-variance-ms: 200
    delete-base-delay-ms: 100
    delete-max-variance-ms: 150
  
  analytics:
    event-address: app.worker.analytics-report
    database-query-delay-ms: 2000
    file-processing-delay-ms: 1000
    execution-timeout-ms: 500
    max-products: 1000
    min-products: 100
    max-revenue: 100000
    max-order-value: 500
    min-order-value: 50
    request-expiration-ms: 3600000
  
  validation:
    max-name-length: 100
    batch-processed-records: 1000
  
  deployment:
    enable-event-loop-pool-auto-sizing: true
    worker-pool-size-multiplier: 2
    max-event-loop-execute-time-ms: 5000
    blocked-thread-check-interval-ms: 1000
    warning-exception-time-ms: 5000
    enable-app-verticle-auto-sizing: true
    app-verticle-instance-divisor: 2
    min-app-verticle-instances: 1
    worker-pool-name: app-worker-pool
    shutdown-timeout-seconds: 30