package com.github.kaivu.vertxweb.domain;

import io.vertx.core.json.JsonObject;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Domain record representing a product.
 *
 * <p>This is the canonical type flowing between the repository and service layers.
 * Routers receive {@link JsonObject} via {@link #toJsonObject()} — conversion happens
 * at the service boundary, keeping this record free of HTTP concerns.
 *
 * <p>Use {@link #forCreate} to construct a Product that has not yet been persisted
 * (productId and createdAt are null; the repository generates them on INSERT).
 */
public record Product(
        String productId,
        String name,
        String category,
        BigDecimal price,
        int quantity,
        boolean inStock,
        LocalDateTime createdAt) {

    /** Factory for new, unsaved products — productId and createdAt are generated by the repo. */
    public static Product forCreate(String name, String category, BigDecimal price, int quantity, boolean inStock) {
        return new Product(null, name, category, price, quantity, inStock, null);
    }

    /** Converts this domain record to the wire format used by service and router layers. */
    public JsonObject toJsonObject() {
        JsonObject json = new JsonObject()
                .put("productId", productId)
                .put("name", name)
                .put("category", category)
                .put("price", price != null ? price.doubleValue() : null)
                .put("quantity", quantity)
                .put("inStock", inStock);
        if (createdAt != null) {
            json.put("createdAt", createdAt.toString());
        }
        return json;
    }
}
